### ISSUE TITLE
Skip tracing

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#10]
<event description>

# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker
* [x] Confirm speaker is comfortable with the event being recorded for YouTube
* [x] Get talk summary and any neat images available
* [x] Add details to Meetup.com
* [ ] Post event to Facebook

## 2 weeks out

* [ ] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Schedule appropriate FB posts for promotion

## 1 week out

* [ ] Post request for volunteers on Facebook and Twitter
  * [x] Record
  * [ ] Photograph
* [x] Check catering stock and order more if required

## Day before

* [x] Check venue details
* [x] Create intro slides - @drzax

## Day of

* [x] Purchase ice - @drzax
* [x] Setup venue (start about 4:30pm) - @drzax
