### ISSUE TITLE
August 22, 2018

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#15]
# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker
* [ ] Get talk summary and any neat images available
* [x] Add details to Meetup.com
* [ ] Post event to Facebook

## 2 weeks out

* [ ] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Schedule appropriate FB posts for promotion

## 1 week out

* [ ] Post request for volunteers on Facebook and Twitter
  * [ ] Record
  * [ ] Photograph
* [x] Check catering stock and order more if required

## Day before

* [x] Check venue details
* [x] Create intro slides

## Day of

* [x] Purchase ice
* [x] Setup venue (start about 4:30pm)
