### ISSUE TITLE
Deepfakes: has the world as we know it changed forever?

### ISSUE THREAD

**Issue by antmandan** [quantsquills/meetups#17]
<event description>

# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker
* [x] Get talk summary and any neat images available
* [x] Add details to Meetup.com
* [x] Post event to Facebook

## 2 weeks out

* [x] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Schedule appropriate FB posts for promotion

## 1 week out

* [ ] Post request for volunteers on Facebook and Twitter
  * [x] Record
  * [ ] Photograph
* [x] Check catering stock and order more if required

## Day before

* [x] Check venue details
* [ ] Create intro slides

## Day of

* [x] Purchase ice
* [x] Setup venue (start about 4:30pm)

**Comment by drzax** [comment]
I've locked in Tim Leslie (@TLes) for September. And working on getting @nathanhoad in the mix too.

**Comment by nathanhoad** [comment]
I'm up for it but Tim can do most of the talking.
