### ISSUE TITLE
Simulating Instagram's algorithmic culture by examining Brisbane's nightlife

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#2]
# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker - it's @antmandan 
* [x] Get talk summary and any neat images available
* [x] Add details to Meetup.com - [done](https://www.meetup.com/Hacks-Hackers-Brisbane/events/249890339/)
* [x] Post event on Facebook - [done](https://www.facebook.com/events/409681112827659/permalink/409761299486307/)

## 2 weeks out

* [ ] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Schedule appropriate FB posts for promotion

## 1 week out

* [x] Post request for volunteers on Facebook and Twitter
  * [x] Record
  * [ ] Photograph
* [x] Check catering stock and order more if required (do this now or you'll have to lug it by hand, which is much more effort) @drzax

## Day before

* [x] Check venue details @drzax
* [x] Create intro slides @drzax

## Day of

* [x] Purchase ice @antmandan 
* [x] Setup venue (start about 4:30pm)

**Comment by drzax** [comment]
/remind me to check drink stock on Monday

**Comment by drzax** [comment]
It's looking more likely that I won't be here for the duration of this event, but I will be around to do setup. Hopefully @rosieryan can be around for building access to do pack up—otherwise, just stack things neat in the foyer and I'll get sorted next morning.

@antmandan Are you right to grab a couple of bags of ice on the way? I'll sort out some soft drinks and I think we're right otherwise.

**Comment by drzax** [comment]
Oh, one more thing—no luck yet finding a volunteer to record this. Would be great if you know anybody to ask.

**Comment by drzax** [comment]
Hey—good work running this one @rosieryan and @antmandan.
