### ISSUE TITLE
February 2019: A ride along with NASA

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#24]
Jonathan Webb, ABC RN's science editor, recently rode along with NASA and has produced a podcast, online piece and more. He will present a behind the scenes/making of this story.

# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker
* [ ] Get talk summary and any neat images available
* [ ] Add details to Meetup.com
* [ ] Post event to Facebook

## 2 weeks out

* [ ] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Schedule appropriate FB posts for promotion
* Notify event partners about the event topic for cross promotion
  * [ ] Women In Media

## 1 week out

* Post request for volunteers on Facebook and Twitter
  * [ ] Record
  * [ ] Photograph
* [ ] Check catering stock and order more if required

## Day before

* [ ] Check venue details
* [ ] Create intro slides

## Day of

* [ ] Purchase ice
* [ ] Setup venue (start about 4:30pm)
* [ ] Check of attendees on arrival

**Comment by kcassowary** [comment]
This will be so good! Do you expect this will be our Feb meetup?

**Comment by drzax** [comment]
Yes, I hope so. Trying to lock things down today. Jonathan is in Bris the
week starting 18th, so we may have to bring the event forward a week. 😳

**Comment by kcassowary** [comment]
I will start newsletter drafting!

**Comment by kcassowary** [comment]
@drzax Have you locked down things with Jonathan? Will it be next week?

I've started an newsletter draft in Mailchimp, so just wondering if I need to crack on over the weekend, with some help from y'all on what links to include, extra info etc

**Comment by drzax** [comment]
It's locked in, thanks. I've been trying to get the event listing up but
haven't got description and title back from Jonathan yet. Hoping to have it
today.

**Comment by jonathanjbwebb** [comment]
Yep sorry @drzax and all. Been a busy week! Emailing some details now.

**Comment by drzax** [comment]
Calling this complete. :-)
