### ISSUE TITLE
March 2019: Storytelling, innovation and the law

### ISSUE THREAD

**Issue by rosieryan** [quantsquills/meetups#25]
<event description>

# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker
* [x] Get talk summary and any neat images available
* [x] Add details to Meetup.com
* [x] Post event to Facebook

## 2 weeks out

* [ ] Schedule appropriate tweets for promotion (in TweetDeck)
* [x] Send email newsletter
* [ ] Schedule appropriate FB posts for promotion
* Notify event partners about the event topic for cross promotion
  * [ ] Women In Media

## 1 week out

* Post request for volunteers on Facebook and Twitter
  * [ ] Record
  * [ ] Photograph
* [x] Check catering stock and order more if required

## Day before

* [ ] Check venue details
* [ ] Create intro slides

## Day of

* [x] Purchase ice
* [x] Setup venue (start about 4:30pm)
* [x] Check of attendees on arrival

**Comment by kcassowary** [comment]
For this checklist, can we add checkboxes for newsletter stuff...? Maybe for two weeks out?

**Comment by drzax** [comment]
Good idea. I've added it to this checklist and to the checklist template.

FYI you can propose an edit to the template at any time: https://github.com/quantsquills/meetups/blob/master/.github/ISSUE_TEMPLATE/event_checklist.md

**Comment by kcassowary** [comment]
Latest newsletter [is out](https://us20.campaign-archive.com/?u=b159620fe75ddd72734247f92&id=35bdf7436d). @drzax did we get any feedback via the quants email from last time? (Just curious...)

**Comment by drzax** [comment]
Thanks Katie. No feedback on the email, I don't think.
