### ISSUE TITLE
Political Manipulation by Twitter Bots & Trolls During Elections

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#27]
<event description>

# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker
* [x] Get talk summary and any neat images available
* [x] Add details to Meetup.com
* [x] Post event to Facebook

## 2 weeks out

* [x] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Send email newsletter
* [ ] Schedule appropriate FB posts for promotion
* Notify event partners about the event topic for cross promotion
  * [ ] Women In Media

## 1 week out

* Post request for volunteers on Facebook and Twitter
  * [ ] Record
  * [ ] Photograph
* [ ] Check catering stock and order more if required

## Day before

* [ ] Check venue details
* [ ] Create intro slides

## Day of

* [ ] Purchase ice
* [ ] Setup venue (start about 4:30pm)
* [ ] Check of attendees on arrival
