### ISSUE TITLE
July 2019: Panel on surveillance of journalists

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#28]
The troubling consequences of the Australian Government's ongoing and well advanced campaign to extend government surveillance powers are finally beginning to dawn on Australia's media companies.

What are the problems, what can journalists do now to protect themselves and their sources, and how should the media go about advocating for change?

# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker
* [x] Get talk summary and any neat images available
* [x] Add details to Meetup.com
* [x] Post event to Facebook

## 2 weeks out

* [x] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Send email newsletter
* [ ] Schedule appropriate FB posts for promotion
* Notify event partners about the event topic for cross promotion
  * [ ] Women In Media

## 1 week out

* Post request for volunteers on Facebook and Twitter
  * [ ] Record
  * [ ] Photograph
* [ ] Check catering stock and order more if required

## Day before

* [ ] Check venue details
* [ ] Create intro slides

## Day of

* [ ] Purchase ice
* [ ] Setup venue (start about 4:30pm)
* [ ] Check of attendees on arrival
