### ISSUE TITLE
Podcasting with ABC's Audio Studios

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#4]
Two Kelly Riordan and Andrew Davies from ABC's Audio Studios will tell us all about podcasting.

# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* [x] Lock in speaker
* [x] Make contact and coordinate with [Brisbane podcast meetup](https://www.meetup.com/Brisbane-Podcasters/)
* [x] Get talk summary and any neat images available
* [x] Add details to Meetup.com
* [x] Post event to Facebook

## 2 weeks out

* [ ] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Schedule appropriate FB posts for promotion

## 1 week out

* [ ] Post request for volunteers on Facebook and Twitter
  * [x] Record
  * [ ] Photograph
* [x] Check catering stock and order more if required

## Day before

* [x] Check venue details
* [x] Create intro slides

## Day of

* [x] Purchase ice
* [x] Setup venue (start about 4:30pm)

**Comment by drzax** [comment]
We have ABC making an audio recording of this one. But no video :-(

**Comment by drzax** [comment]
A great success. This had >50 attendees. I've opened #7 to make sure we do something with the audio recording.
