### ISSUE TITLE
Making the jump to digital/technical/data journalism

### ISSUE THREAD

**Issue by drzax** [quantsquills/meetups#6]
A panel session with 4-5 people who have come from more traditional journalism to be leaders in the use of technical skills and tools in the reporting and production of their journalism. This follows from the proposal in #3.

# To-do

## 5 weeks out

This stuff should get done early so we can promote the next event at the on that's about to happen.

* (@rosieryan) Lock in panelists
  * [x] @rosieryan to moderate
  * [x] @CristenT
  * [x] Felicity Caldwell
* [ ] Get talk summary and any neat images available
* [x] (@drzax) Add details to Meetup.com
* [ ] Post event to Facebook

## 2 weeks out

* [ ] Schedule appropriate tweets for promotion (in TweetDeck)
* [ ] Schedule appropriate FB posts for promotion

## 1 week out

* Post request for volunteers on Facebook and Twitter
  * [ ] Record
  * [ ] Photograph
* [ ] Check catering stock and order more if required

## Day before

* [ ] Check venue details
* [ ] Create intro slides

## Day of

* [x] Purchase ice
* [ ] Setup venue (start about 4:30pm)

**Comment by drzax** [comment]
We've had an offer to record this one (and maybe future ones) from Nick Coleman at ABC.

**Comment by drzax** [comment]
I think we need one or two more panellists for this—suggestions welcome.

**Comment by antmandan** [comment]
What about Natalie Bochenski?

**Comment by drzax** [comment]
Closing this now. Here's the video: https://www.youtube.com/watch?v=Qp9ENsOGdSY&feature=youtu.be
